// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcZnEStxmd-qxYiYr1LLgJBKJkdNMudLk',
    appId: '1:560003464914:web:9b8938daad336959e4770b',
    messagingSenderId: '560003464914',
    projectId: 'fire-authentication-d895f',
    authDomain: 'fire-authentication-d895f.firebaseapp.com',
    storageBucket: 'fire-authentication-d895f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBbSDqtNf1fsyKyYr__8jqAVUhJkfAlfc',
    appId: '1:560003464914:android:fd8aac6fb398c921e4770b',
    messagingSenderId: '560003464914',
    projectId: 'fire-authentication-d895f',
    storageBucket: 'fire-authentication-d895f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNH5QgY2iDXClq1EoANhDlOgWD5nVLw9E',
    appId: '1:560003464914:ios:3c6238b32882840ee4770b',
    messagingSenderId: '560003464914',
    projectId: 'fire-authentication-d895f',
    storageBucket: 'fire-authentication-d895f.firebasestorage.app',
    iosBundleId: 'task1.com.task1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNH5QgY2iDXClq1EoANhDlOgWD5nVLw9E',
    appId: '1:560003464914:ios:3c6238b32882840ee4770b',
    messagingSenderId: '560003464914',
    projectId: 'fire-authentication-d895f',
    storageBucket: 'fire-authentication-d895f.firebasestorage.app',
    iosBundleId: 'task1.com.task1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcZnEStxmd-qxYiYr1LLgJBKJkdNMudLk',
    appId: '1:560003464914:web:49e590ade4a0d9d7e4770b',
    messagingSenderId: '560003464914',
    projectId: 'fire-authentication-d895f',
    authDomain: 'fire-authentication-d895f.firebaseapp.com',
    storageBucket: 'fire-authentication-d895f.firebasestorage.app',
  );
}
